/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;

/**
 *
 * @author ezequielpena
 */
public class About extends javax.swing.JPanel {

    /**
     * Creates new form About
     */
    public About() {
        initComponents();
         setLayout(new BorderLayout());
        setBackground(Color.BLACK);
        setBorder(BorderFactory.createEmptyBorder()); 

        JTextPane textPane = new JTextPane();
        textPane.setContentType("text/html");
        textPane.setText("""
            <html>
                <body style='background-color:#000000; color:#FFFFFF; font-family:poppins; font-size:13px; margin: 30; padding: 0;'>
                    <h2 style='color:#00FF00;'>About CodeGen</h2>
                    <p><b>CodeGen</b> is a tool designed to automate the creation of <b>JPA</b> classes for <b>Spring Boot</b> projects.</p>
                    <p>You only need to register the database you want to connect to, and the program will automatically generate both the <b style='color:#00BFFF;'>Entity</b> class and the <b style='color:#FF4500;'>Repository</b> interface.</p>
                    <p style='color:#00FF00;'><b>Why is it useful?</b></p>
                    <ul>
                        <li>Avoids writing repetitive boilerplate code manually</li>
                        <li>Saves development time</li>
                        <li>Reduces human errors</li>
                        <li>Enables fast generation of JPA structures</li>
                        <li>Follows best practices in code generation</li>
                    </ul>
                    <p><b style='color:#00FF00;'>Technologies used:</b><br>
                    Java 21, Swing, Maven, PostgreSQL, JPA, Spring Boot</p>
                    <p><b style='color:#00FF00;'>Authors:</b><br>
                    Ezequiel Peña Mazariegos<br>
                    Mario Alfonso Ramírez Moreno</p>
                    <p><b style='color:#00FF00;'>Collaborators:</b><br>
                    Jesús Arnulfo Zacarías Santos</p>
                    <p><b style='color:#00FF00;'>Contact:</b><br>
                    codegen@gmail.com</p>
                    <p><b style='color:#00FF00;'>License:</b><br>
                    MIT License</p>
                    <p><b style='color:#00FF00;'>Version:</b><br>
                    1.0.0</p>
                    <p><b style='color:#00FF00;'>System requirements:</b><br>
                    Java 21, PostgreSQL, and Maven</p>
                    <p><b style='color:#00FF00;'>How to use:</b><br>
                    1. Register your database connection.<br>
                    2. Click on 'Generate Entity' and 'Generate Repository'.<br>
                    3. Use the generated code in your Spring Boot project.</p>
                    <p><b style='color:#00FF00;'>Upcoming:</b><br>
                    Soon to be available in a web version!</p>
                </body>
            </html>
        """);
        textPane.setEditable(false);
        textPane.setOpaque(false);
        textPane.setBorder(BorderFactory.createEmptyBorder()); 
        textPane.setCaretPosition(0);

        JScrollPane scrollPane = new JScrollPane(textPane);
        scrollPane.setBorder(BorderFactory.createEmptyBorder());
        scrollPane.setViewportBorder(null);
        scrollPane.setOpaque(false);
        scrollPane.getViewport().setOpaque(false);

        scrollPane.getVerticalScrollBar().setUI(null);
        scrollPane.getHorizontalScrollBar().setUI(null);

        add(scrollPane, BorderLayout.CENTER);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(31, 31, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
