/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Insets;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTextArea;
import javax.swing.JTextPane;
import javax.swing.border.EmptyBorder;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author ezequielpena
 */
public class Activity extends javax.swing.JPanel {

    /**
     * Creates new form Activity
     */
    private JTextPane logTextPane;
    private JScrollPane scrollPane;
    private JLabel titleLabel;
    private JSeparator separator;
    
    public Activity() {
        initComponents();
        setupActivityLogViewer();
        loadLogContent();;
    }
     private void setupActivityLogViewer() {
        setLayout(new BorderLayout());
        setBackground(new Color(31, 31, 31));

        titleLabel = new JLabel("Activity Log");
        titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 18));
        titleLabel.setForeground(new Color(0, 255, 0));
        titleLabel.setBorder(new EmptyBorder(15, 15, 5, 0));

        separator = new JSeparator();
        separator.setForeground(new Color(80, 80, 80));
        separator.setBackground(new Color(80, 80, 80));

        logTextPane = new JTextPane();
        logTextPane.setEditable(false);
        logTextPane.setBackground(new Color(31, 31, 31));
        logTextPane.setFont(new Font("Consolas", Font.PLAIN, 13));

        scrollPane = new JScrollPane(logTextPane);
        scrollPane.setBorder(null);
        scrollPane.setBackground(new Color(31, 31, 31));
        scrollPane.getVerticalScrollBar().setUnitIncrement(16);
        scrollPane.getVerticalScrollBar().setBackground(new Color(20, 20, 20));

        JPanel topPanel = new JPanel(new BorderLayout());
        topPanel.setBackground(new Color(31, 31, 31));
        topPanel.add(titleLabel, BorderLayout.NORTH);
        topPanel.add(separator, BorderLayout.SOUTH);

        add(topPanel, BorderLayout.NORTH);
        add(scrollPane, BorderLayout.CENTER);
    }

    private void loadLogContent() {
        StyledDocument doc = logTextPane.getStyledDocument();

    // Estilos
    Style defaultStyle = doc.addStyle("default", null);
    StyleConstants.setForeground(defaultStyle, Color.WHITE);

    Style errorStyle = doc.addStyle("error", null);
    StyleConstants.setForeground(errorStyle, Color.RED);

    Style createStyle = doc.addStyle("create", null);
    StyleConstants.setForeground(createStyle, Color.GREEN); 

    Style updateStyle = doc.addStyle("update", null);
    StyleConstants.setForeground(updateStyle, new Color(0, 191, 255)); 

    Style deleteStyle = doc.addStyle("delete", null);
    StyleConstants.setForeground(deleteStyle, new Color(255, 69, 0)); 

    try (BufferedReader reader = new BufferedReader(new FileReader("activity.log"))) {
        String line;
        while ((line = reader.readLine()) != null) {
            String lowerLine = line.toLowerCase();
            Style styleToUse = defaultStyle;
            String icon = "🔹 "; // ícono por defecto

            if (lowerLine.contains("error")) {
                styleToUse = errorStyle;
                icon = "❌ ";
            } else if (lowerLine.contains("create")) {
                styleToUse = createStyle;
                icon = "✔️ ";
            } else if (lowerLine.contains("update")) {
                styleToUse = updateStyle;
                icon = "✏️ ";
            } else if (lowerLine.contains("delete")) {
                styleToUse = deleteStyle;
                icon = "🗑️ ";
            }

            doc.insertString(doc.getLength(), icon + line + "\n", styleToUse);
        }
    } catch (IOException | BadLocationException e) {
        try {
            doc.insertString(doc.getLength(), "❌ Failed to read activity log.\n", errorStyle);
        } catch (BadLocationException ex) {
            
        }
    }

    logTextPane.setCaretPosition(doc.getLength()); // auto-scroll
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(31, 31, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
