/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.TableViewListController;

/**
 *
 * @author ezequielpena
 */
public class TableViewList extends javax.swing.JPanel {

    /**
     * Creates new form TableViewList
     */
    public TableViewListController objTableViewListController;
    public TableViewList() {
        initComponents();
        this.objTableViewListController = new TableViewListController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameTable = new javax.swing.JLabel();
        generateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(31, 31, 31));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(31, 31, 31));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameTable.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        nameTable.setForeground(new java.awt.Color(102, 255, 255));
        nameTable.setText("Name table");
        jPanel1.add(nameTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 19, -1, -1));

        generateButton.setBackground(new java.awt.Color(153, 255, 51));
        generateButton.setText("Generate code");
        generateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(generateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 19, 151, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/ezequielpena/NetBeansProjects/generador_codigo_java_maven/src/resources/icons/tableIcon.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 12, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton generateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel nameTable;
    // End of variables declaration//GEN-END:variables
}
